# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0b\x62ookings.v1\"\x1f\n\x11GetBookingRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x12GetBookingResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2`\n\x0f\x42ookingsService\x12M\n\nGetBooking\x12\x1e.bookings.v1.GetBookingRequest\x1a\x1f.bookings.v1.GetBookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKINGREQUEST']._serialized_start=30
  _globals['_GETBOOKINGREQUEST']._serialized_end=61
  _globals['_GETBOOKINGRESPONSE']._serialized_start=63
  _globals['_GETBOOKINGRESPONSE']._serialized_end=111
  _globals['_BOOKINGSSERVICE']._serialized_start=113
  _globals['_BOOKINGSSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
