replicaCount: 3

image:
  repository: reviews-app
  tag: "prod"

service:
  type: ClusterIP
  port: 8109

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "1000m"
