events {}

http {
    server {
        listen 80;

        location /api/shipments {
            proxy_pass http://shipments-svc-s07:8230/shipments;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 'gateway ok';
            add_header Content-Type text/plain;
        }
    }
}
